### PR TITLE
Fibonacci Sequence

### PR DESCRIPTION
**Pull request by kanowicka**

### CODE REVIEW

**Review by TomaszBurnejko — CHANGES_REQUESTED** [review]
**IndexError: list index out of range** po wpisaniu "-1" 
warto by dodać sprawdzenie if n<0, ValueError jakis z tego co pamietam

**Review by kanowicka — COMMENTED** [review]
Good point! Changes applied.

**Review by TomaszBurnejko — APPROVED** [review]
there is also an option(please ty again) that the program should work in the case of a string or negative number and finish the work only after entering the correct number/but I do not know if it is necessary

**Comment by kanowicka** [comment]
@TomaszBurnejko ready

**Review by TomaszBurnejko — APPROVED** [review]

**Pull request merged**
